include:
  - board: xiao_ble//zmk
    shield: Pyuron_R rgbled_adapter
  - board: xiao_ble//zmk
    shield: Pyuron_L rgbled_adapter
  - board: xiao_ble//zmk
    shield: Pyuron_D prospector_adapter
  - board: xiao_ble//zmk
    shield: settings_reset
 
